version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: sentinel
      POSTGRES_USER: sentinel
      POSTGRES_PASSWORD: sentinel
    ports:
    - "5432:5432"
    volumes:
    - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
    - "6379:6379"

  api:
    build: ./api
    ports:
    - "3001:3001"
    environment:
      DATABASE_URL: postgresql://sentinel:sentinel@postgres:5432/sentinel
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis
    volumes:
      - ./api:/app
      - ./fixtures:/app/fixtures
      - /app/node_modules

  web:
    build: ./web
    ports:
      - "5173:5173"
    depends_on:
      - api
    environment:
      VITE_API_BASE: http://api:3001
    volumes:
      - ./web:/web
      - /web/node_modules

volumes:
  pgdata:
